{
 "title": "GitHub Actions Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "repo",
    "label": "Repository",
    "query": {
     "query": "label_values(github_repo_workflows,repo)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(github_repo_workflow_runs{repo=~\"$repo\"},status)"
    }
   },
   {
    "name": "conclusion",
    "label": "Conclusion",
    "query": {
     "query": "label_values(github_repo_workflow_runs{repo=~\"$repo\"},conclusion)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queued runs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_workflow_runs{status=\"queued\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In progress runs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_workflow_runs{status=\"in_progress\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure runs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_workflow_runs{conclusion=\"failure\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success runs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_workflow_runs{conclusion=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GitHub workflow run status",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  github_repo_workflow_runs{repo=~\"${repo}\", status=~\"${status}\", conclusion=~\"${conclusion}\"}\n) by(name, repo, status, conclusion)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}