apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "github-actions-exporter"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "github-actions-exporter"
  labels:
    app.kubernetes.io/name: "github-actions-exporter"
spec:
  selector:
    app.kubernetes.io/name: "github-actions-exporter"
  ports:
    - name: "http"
      port: 8080
      protocol: "TCP"
      targetPort: "http"

---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "github-actions-exporter"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "github-actions-exporter"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "github-actions-exporter"
      annotations:
        promtail.io/collect: "true"
    spec:
      serviceAccountName: "github-actions-exporter"
      automountServiceAccountToken: false
      containers:
        - name: "github-actions-exporter"
          image: "shadowuser17/github-actions-exporter:latest"
          imagePullPolicy: "Always"
          env:
            - name: "DEBUG_MODE"
              value: ""
            - name: "HTTP_ADDR"
              value: "0.0.0.0"
            - name: "HTTP_PORT"
              value: "8080"
            - name: "GITHUB_ORG"
              value: ""
            - name: "GITHUB_TOKEN"
              value: ""
            - name: "SCRAPE_INTERVAL"
              value: "120"
            - name: "GITHUB_REPOS_TYPE"
              value: "sources"
            - name: "GITHUB_RUNS_STATUS"
              value: ""
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 8080
