apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "github-actions-exporter"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "github-actions-exporter"
  labels:
    app.kubernetes.io/name: "github-actions-exporter"
spec:
  selector:
    app.kubernetes.io/name: "github-actions-exporter"
  ports:
    - name: "http"
      port: 8080
      protocol: "TCP"
      targetPort: "http"

---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "github-actions-exporter"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "github-actions-exporter"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "github-actions-exporter"
      annotations:
        promtail.io/collect: "true"
    spec:
      serviceAccountName: "github-actions-exporter"
      automountServiceAccountToken: false
      containers:
        - name: "github-actions-exporter"
          image: "shadowuser17/github-actions-exporter:latest"
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: "github-actions-exporter"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            httpGet:
              path: "/metrics"
              port: "http"
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            httpGet:
              path: "/metrics"
              port: "http"
